
namespace PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_
{
    partial class form_Principal
    {
        /// <summary>
        /// Variável de designer necessária.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpar os recursos que estão sendo usados.
        /// </summary>
        /// <param name="disposing">true se for necessário descartar os recursos gerenciados; caso contrário, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código gerado pelo Windows Form Designer

        /// <summary>
        /// Método necessário para suporte ao Designer - não modifique 
        /// o conteúdo deste método com o editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(form_Principal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.pnlDesktop = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnMinimizarJanela = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFecharJanela = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlMenu = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnFinanceiro = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCadastrarServicos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCadastrarMateriais = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCadastrarClientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOpcoesMenu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1.SuspendLayout();
            this.pnlMenu.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Verdana", 12F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(53)))), ((int)(((byte)(53)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(23, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(208, 18);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Marmoraria Bellas Pedras  ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(53)))), ((int)(((byte)(53)))));
            this.bunifuGroupBox1.BorderRadius = 5;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(534, 9);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(252, 43);
            this.bunifuGroupBox1.TabIndex = 20;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuGroupBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGroupBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGroupBox1, "");
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.White;
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = "Cadastrar Clientes";
            // 
            // pnlDesktop
            // 
            this.pnlDesktop.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlDesktop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlDesktop.BackgroundImage")));
            this.pnlDesktop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlDesktop.BorderColor = System.Drawing.Color.Transparent;
            this.pnlDesktop.BorderRadius = 3;
            this.pnlDesktop.BorderThickness = 1;
            this.pnlDesktop.Location = new System.Drawing.Point(64, 72);
            this.pnlDesktop.Name = "pnlDesktop";
            this.pnlDesktop.ShowBorders = true;
            this.pnlDesktop.Size = new System.Drawing.Size(1202, 562);
            this.pnlDesktop.TabIndex = 21;
            this.bunifuToolTip1.SetToolTip(this.pnlDesktop, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pnlDesktop, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pnlDesktop, "");
            // 
            // btnMinimizarJanela
            // 
            this.btnMinimizarJanela.AllowAnimations = true;
            this.btnMinimizarJanela.AllowMouseEffects = true;
            this.btnMinimizarJanela.AllowToggling = false;
            this.btnMinimizarJanela.AnimationSpeed = 200;
            this.btnMinimizarJanela.AutoGenerateColors = false;
            this.btnMinimizarJanela.AutoRoundBorders = false;
            this.btnMinimizarJanela.AutoSizeLeftIcon = true;
            this.btnMinimizarJanela.AutoSizeRightIcon = true;
            this.btnMinimizarJanela.BackColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.BackColor1 = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMinimizarJanela.BackgroundImage")));
            this.btnMinimizarJanela.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimizarJanela.ButtonText = "";
            this.btnMinimizarJanela.ButtonTextMarginLeft = 0;
            this.btnMinimizarJanela.ColorContrastOnClick = 45;
            this.btnMinimizarJanela.ColorContrastOnHover = 45;
            this.btnMinimizarJanela.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnMinimizarJanela.CustomizableEdges = borderEdges1;
            this.btnMinimizarJanela.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMinimizarJanela.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMinimizarJanela.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnMinimizarJanela.ForeColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMinimizarJanela.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMinimizarJanela.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMinimizarJanela.IconMarginLeft = 11;
            this.btnMinimizarJanela.IconPadding = 10;
            this.btnMinimizarJanela.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMinimizarJanela.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMinimizarJanela.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMinimizarJanela.IconSize = 25;
            this.btnMinimizarJanela.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.IdleBorderRadius = 1;
            this.btnMinimizarJanela.IdleBorderThickness = 1;
            this.btnMinimizarJanela.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_subtração_90;
            this.btnMinimizarJanela.IdleIconRightImage = null;
            this.btnMinimizarJanela.IndicateFocus = false;
            this.btnMinimizarJanela.Location = new System.Drawing.Point(1178, -1);
            this.btnMinimizarJanela.Name = "btnMinimizarJanela";
            this.btnMinimizarJanela.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnDisabledState.BorderRadius = 1;
            this.btnMinimizarJanela.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimizarJanela.OnDisabledState.BorderThickness = 1;
            this.btnMinimizarJanela.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnDisabledState.IconLeftImage = null;
            this.btnMinimizarJanela.OnDisabledState.IconRightImage = null;
            this.btnMinimizarJanela.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnMinimizarJanela.onHoverState.BorderRadius = 1;
            this.btnMinimizarJanela.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimizarJanela.onHoverState.BorderThickness = 1;
            this.btnMinimizarJanela.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnMinimizarJanela.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnMinimizarJanela.onHoverState.IconLeftImage = null;
            this.btnMinimizarJanela.onHoverState.IconRightImage = null;
            this.btnMinimizarJanela.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnIdleState.BorderRadius = 1;
            this.btnMinimizarJanela.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimizarJanela.OnIdleState.BorderThickness = 1;
            this.btnMinimizarJanela.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_subtração_90;
            this.btnMinimizarJanela.OnIdleState.IconRightImage = null;
            this.btnMinimizarJanela.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnPressedState.BorderRadius = 1;
            this.btnMinimizarJanela.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMinimizarJanela.OnPressedState.BorderThickness = 1;
            this.btnMinimizarJanela.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnMinimizarJanela.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMinimizarJanela.OnPressedState.IconLeftImage = null;
            this.btnMinimizarJanela.OnPressedState.IconRightImage = null;
            this.btnMinimizarJanela.Size = new System.Drawing.Size(41, 35);
            this.btnMinimizarJanela.TabIndex = 17;
            this.btnMinimizarJanela.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMinimizarJanela.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMinimizarJanela.TextMarginLeft = 0;
            this.btnMinimizarJanela.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnMinimizarJanela, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnMinimizarJanela, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnMinimizarJanela, "");
            this.btnMinimizarJanela.UseDefaultRadiusAndThickness = true;
            this.btnMinimizarJanela.Click += new System.EventHandler(this.btnMinimizarJanela_Click);
            // 
            // btnFecharJanela
            // 
            this.btnFecharJanela.AllowAnimations = true;
            this.btnFecharJanela.AllowMouseEffects = true;
            this.btnFecharJanela.AllowToggling = false;
            this.btnFecharJanela.AnimationSpeed = 200;
            this.btnFecharJanela.AutoGenerateColors = false;
            this.btnFecharJanela.AutoRoundBorders = false;
            this.btnFecharJanela.AutoSizeLeftIcon = true;
            this.btnFecharJanela.AutoSizeRightIcon = true;
            this.btnFecharJanela.BackColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFecharJanela.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFecharJanela.BackgroundImage")));
            this.btnFecharJanela.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFecharJanela.ButtonText = "";
            this.btnFecharJanela.ButtonTextMarginLeft = 0;
            this.btnFecharJanela.ColorContrastOnClick = 45;
            this.btnFecharJanela.ColorContrastOnHover = 45;
            this.btnFecharJanela.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnFecharJanela.CustomizableEdges = borderEdges2;
            this.btnFecharJanela.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFecharJanela.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFecharJanela.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnFecharJanela.ForeColor = System.Drawing.Color.White;
            this.btnFecharJanela.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFecharJanela.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFecharJanela.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFecharJanela.IconMarginLeft = 11;
            this.btnFecharJanela.IconPadding = 10;
            this.btnFecharJanela.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFecharJanela.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFecharJanela.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFecharJanela.IconSize = 25;
            this.btnFecharJanela.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.IdleBorderRadius = 1;
            this.btnFecharJanela.IdleBorderThickness = 1;
            this.btnFecharJanela.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_excluir_100__1_;
            this.btnFecharJanela.IdleIconRightImage = null;
            this.btnFecharJanela.IndicateFocus = false;
            this.btnFecharJanela.Location = new System.Drawing.Point(1225, -1);
            this.btnFecharJanela.Name = "btnFecharJanela";
            this.btnFecharJanela.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnDisabledState.BorderRadius = 1;
            this.btnFecharJanela.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFecharJanela.OnDisabledState.BorderThickness = 1;
            this.btnFecharJanela.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnDisabledState.IconLeftImage = null;
            this.btnFecharJanela.OnDisabledState.IconRightImage = null;
            this.btnFecharJanela.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(53)))), ((int)(((byte)(53)))));
            this.btnFecharJanela.onHoverState.BorderRadius = 1;
            this.btnFecharJanela.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFecharJanela.onHoverState.BorderThickness = 1;
            this.btnFecharJanela.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(53)))), ((int)(((byte)(53)))));
            this.btnFecharJanela.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFecharJanela.onHoverState.IconLeftImage = null;
            this.btnFecharJanela.onHoverState.IconRightImage = null;
            this.btnFecharJanela.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnIdleState.BorderRadius = 1;
            this.btnFecharJanela.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFecharJanela.OnIdleState.BorderThickness = 1;
            this.btnFecharJanela.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFecharJanela.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_excluir_100__1_;
            this.btnFecharJanela.OnIdleState.IconRightImage = null;
            this.btnFecharJanela.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnPressedState.BorderRadius = 1;
            this.btnFecharJanela.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFecharJanela.OnPressedState.BorderThickness = 1;
            this.btnFecharJanela.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnFecharJanela.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFecharJanela.OnPressedState.IconLeftImage = null;
            this.btnFecharJanela.OnPressedState.IconRightImage = null;
            this.btnFecharJanela.Size = new System.Drawing.Size(41, 35);
            this.btnFecharJanela.TabIndex = 1;
            this.btnFecharJanela.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFecharJanela.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFecharJanela.TextMarginLeft = 0;
            this.btnFecharJanela.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnFecharJanela, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnFecharJanela, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnFecharJanela, "");
            this.btnFecharJanela.UseDefaultRadiusAndThickness = true;
            this.btnFecharJanela.Click += new System.EventHandler(this.btnFecharJanela_Click);
            // 
            // pnlMenu
            // 
            this.pnlMenu.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(16)))), ((int)(((byte)(16)))));
            this.pnlMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlMenu.BackgroundImage")));
            this.pnlMenu.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlMenu.BorderColor = System.Drawing.Color.Transparent;
            this.pnlMenu.BorderRadius = 3;
            this.pnlMenu.BorderThickness = 1;
            this.pnlMenu.Controls.Add(this.btnFinanceiro);
            this.pnlMenu.Controls.Add(this.bunifuButton4);
            this.pnlMenu.Controls.Add(this.bunifuButton3);
            this.pnlMenu.Controls.Add(this.btnCadastrarServicos);
            this.pnlMenu.Controls.Add(this.btnCadastrarMateriais);
            this.pnlMenu.Controls.Add(this.btnCadastrarClientes);
            this.pnlMenu.Controls.Add(this.btnOpcoesMenu);
            this.pnlMenu.Location = new System.Drawing.Point(-1, -1);
            this.pnlMenu.Name = "pnlMenu";
            this.pnlMenu.ShowBorders = true;
            this.pnlMenu.Size = new System.Drawing.Size(66, 635);
            this.pnlMenu.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.pnlMenu, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pnlMenu, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pnlMenu, "");
            // 
            // btnFinanceiro
            // 
            this.btnFinanceiro.AllowAnimations = true;
            this.btnFinanceiro.AllowMouseEffects = true;
            this.btnFinanceiro.AllowToggling = false;
            this.btnFinanceiro.AnimationSpeed = 200;
            this.btnFinanceiro.AutoGenerateColors = false;
            this.btnFinanceiro.AutoRoundBorders = false;
            this.btnFinanceiro.AutoSizeLeftIcon = true;
            this.btnFinanceiro.AutoSizeRightIcon = true;
            this.btnFinanceiro.BackColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFinanceiro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFinanceiro.BackgroundImage")));
            this.btnFinanceiro.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinanceiro.ButtonText = "";
            this.btnFinanceiro.ButtonTextMarginLeft = 0;
            this.btnFinanceiro.ColorContrastOnClick = 45;
            this.btnFinanceiro.ColorContrastOnHover = 45;
            this.btnFinanceiro.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnFinanceiro.CustomizableEdges = borderEdges3;
            this.btnFinanceiro.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFinanceiro.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFinanceiro.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnFinanceiro.ForeColor = System.Drawing.Color.White;
            this.btnFinanceiro.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFinanceiro.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFinanceiro.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFinanceiro.IconMarginLeft = 11;
            this.btnFinanceiro.IconPadding = 10;
            this.btnFinanceiro.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFinanceiro.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFinanceiro.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFinanceiro.IconSize = 25;
            this.btnFinanceiro.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.IdleBorderRadius = 12;
            this.btnFinanceiro.IdleBorderThickness = 1;
            this.btnFinanceiro.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_saco_de_dinheiro_100;
            this.btnFinanceiro.IdleIconRightImage = null;
            this.btnFinanceiro.IndicateFocus = false;
            this.btnFinanceiro.Location = new System.Drawing.Point(9, 444);
            this.btnFinanceiro.Name = "btnFinanceiro";
            this.btnFinanceiro.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnDisabledState.BorderRadius = 12;
            this.btnFinanceiro.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinanceiro.OnDisabledState.BorderThickness = 1;
            this.btnFinanceiro.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnDisabledState.IconLeftImage = null;
            this.btnFinanceiro.OnDisabledState.IconRightImage = null;
            this.btnFinanceiro.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnFinanceiro.onHoverState.BorderRadius = 12;
            this.btnFinanceiro.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinanceiro.onHoverState.BorderThickness = 1;
            this.btnFinanceiro.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnFinanceiro.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnFinanceiro.onHoverState.IconLeftImage = null;
            this.btnFinanceiro.onHoverState.IconRightImage = null;
            this.btnFinanceiro.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnIdleState.BorderRadius = 12;
            this.btnFinanceiro.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinanceiro.OnIdleState.BorderThickness = 1;
            this.btnFinanceiro.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFinanceiro.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_saco_de_dinheiro_100;
            this.btnFinanceiro.OnIdleState.IconRightImage = null;
            this.btnFinanceiro.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnPressedState.BorderRadius = 12;
            this.btnFinanceiro.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFinanceiro.OnPressedState.BorderThickness = 1;
            this.btnFinanceiro.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnFinanceiro.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFinanceiro.OnPressedState.IconLeftImage = null;
            this.btnFinanceiro.OnPressedState.IconRightImage = null;
            this.btnFinanceiro.Size = new System.Drawing.Size(50, 43);
            this.btnFinanceiro.TabIndex = 6;
            this.btnFinanceiro.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFinanceiro.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFinanceiro.TextMarginLeft = 0;
            this.btnFinanceiro.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnFinanceiro, "Financeiro");
            this.bunifuToolTip1.SetToolTipIcon(this.btnFinanceiro, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnFinanceiro, "");
            this.btnFinanceiro.UseDefaultRadiusAndThickness = true;
            this.btnFinanceiro.Click += new System.EventHandler(this.btnFinanceiro_Click);
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges4;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.Transparent;
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.IdleBorderRadius = 12;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(9, 381);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnDisabledState.BorderRadius = 12;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton4.onHoverState.BorderRadius = 12;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnIdleState.BorderRadius = 12;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnPressedState.BorderRadius = 12;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(50, 43);
            this.bunifuButton4.TabIndex = 5;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton4, "Cadastrar Serviços");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton4, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton4, "");
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges5;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.Transparent;
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.IdleBorderRadius = 12;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(9, 317);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnDisabledState.BorderRadius = 12;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton3.onHoverState.BorderRadius = 12;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnIdleState.BorderRadius = 12;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnPressedState.BorderRadius = 12;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(50, 43);
            this.bunifuButton3.TabIndex = 4;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton3, "Cadastrar Serviços");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton3, "");
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // btnCadastrarServicos
            // 
            this.btnCadastrarServicos.AllowAnimations = true;
            this.btnCadastrarServicos.AllowMouseEffects = true;
            this.btnCadastrarServicos.AllowToggling = false;
            this.btnCadastrarServicos.AnimationSpeed = 200;
            this.btnCadastrarServicos.AutoGenerateColors = false;
            this.btnCadastrarServicos.AutoRoundBorders = false;
            this.btnCadastrarServicos.AutoSizeLeftIcon = true;
            this.btnCadastrarServicos.AutoSizeRightIcon = true;
            this.btnCadastrarServicos.BackColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCadastrarServicos.BackgroundImage")));
            this.btnCadastrarServicos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarServicos.ButtonText = "";
            this.btnCadastrarServicos.ButtonTextMarginLeft = 0;
            this.btnCadastrarServicos.ColorContrastOnClick = 45;
            this.btnCadastrarServicos.ColorContrastOnHover = 45;
            this.btnCadastrarServicos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCadastrarServicos.CustomizableEdges = borderEdges6;
            this.btnCadastrarServicos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCadastrarServicos.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCadastrarServicos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCadastrarServicos.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarServicos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCadastrarServicos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarServicos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCadastrarServicos.IconMarginLeft = 11;
            this.btnCadastrarServicos.IconPadding = 10;
            this.btnCadastrarServicos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCadastrarServicos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarServicos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCadastrarServicos.IconSize = 25;
            this.btnCadastrarServicos.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.IdleBorderRadius = 12;
            this.btnCadastrarServicos.IdleBorderThickness = 1;
            this.btnCadastrarServicos.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.btnCadastrarServicos.IdleIconRightImage = null;
            this.btnCadastrarServicos.IndicateFocus = false;
            this.btnCadastrarServicos.Location = new System.Drawing.Point(9, 251);
            this.btnCadastrarServicos.Name = "btnCadastrarServicos";
            this.btnCadastrarServicos.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnDisabledState.BorderRadius = 12;
            this.btnCadastrarServicos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarServicos.OnDisabledState.BorderThickness = 1;
            this.btnCadastrarServicos.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnDisabledState.IconLeftImage = null;
            this.btnCadastrarServicos.OnDisabledState.IconRightImage = null;
            this.btnCadastrarServicos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarServicos.onHoverState.BorderRadius = 12;
            this.btnCadastrarServicos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarServicos.onHoverState.BorderThickness = 1;
            this.btnCadastrarServicos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarServicos.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarServicos.onHoverState.IconLeftImage = null;
            this.btnCadastrarServicos.onHoverState.IconRightImage = null;
            this.btnCadastrarServicos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnIdleState.BorderRadius = 12;
            this.btnCadastrarServicos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarServicos.OnIdleState.BorderThickness = 1;
            this.btnCadastrarServicos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarServicos.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_serra_circular_100;
            this.btnCadastrarServicos.OnIdleState.IconRightImage = null;
            this.btnCadastrarServicos.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnPressedState.BorderRadius = 12;
            this.btnCadastrarServicos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarServicos.OnPressedState.BorderThickness = 1;
            this.btnCadastrarServicos.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarServicos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarServicos.OnPressedState.IconLeftImage = null;
            this.btnCadastrarServicos.OnPressedState.IconRightImage = null;
            this.btnCadastrarServicos.Size = new System.Drawing.Size(50, 43);
            this.btnCadastrarServicos.TabIndex = 3;
            this.btnCadastrarServicos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCadastrarServicos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCadastrarServicos.TextMarginLeft = 0;
            this.btnCadastrarServicos.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnCadastrarServicos, "Cadastrar Serviços");
            this.bunifuToolTip1.SetToolTipIcon(this.btnCadastrarServicos, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnCadastrarServicos, "");
            this.btnCadastrarServicos.UseDefaultRadiusAndThickness = true;
            this.btnCadastrarServicos.Click += new System.EventHandler(this.btnCadastrarServicos_Click);
            // 
            // btnCadastrarMateriais
            // 
            this.btnCadastrarMateriais.AllowAnimations = true;
            this.btnCadastrarMateriais.AllowMouseEffects = true;
            this.btnCadastrarMateriais.AllowToggling = false;
            this.btnCadastrarMateriais.AnimationSpeed = 200;
            this.btnCadastrarMateriais.AutoGenerateColors = false;
            this.btnCadastrarMateriais.AutoRoundBorders = false;
            this.btnCadastrarMateriais.AutoSizeLeftIcon = true;
            this.btnCadastrarMateriais.AutoSizeRightIcon = true;
            this.btnCadastrarMateriais.BackColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCadastrarMateriais.BackgroundImage")));
            this.btnCadastrarMateriais.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarMateriais.ButtonText = "";
            this.btnCadastrarMateriais.ButtonTextMarginLeft = 0;
            this.btnCadastrarMateriais.ColorContrastOnClick = 45;
            this.btnCadastrarMateriais.ColorContrastOnHover = 45;
            this.btnCadastrarMateriais.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCadastrarMateriais.CustomizableEdges = borderEdges7;
            this.btnCadastrarMateriais.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCadastrarMateriais.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCadastrarMateriais.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCadastrarMateriais.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarMateriais.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCadastrarMateriais.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarMateriais.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCadastrarMateriais.IconMarginLeft = 11;
            this.btnCadastrarMateriais.IconPadding = 10;
            this.btnCadastrarMateriais.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCadastrarMateriais.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarMateriais.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCadastrarMateriais.IconSize = 25;
            this.btnCadastrarMateriais.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.IdleBorderRadius = 12;
            this.btnCadastrarMateriais.IdleBorderThickness = 1;
            this.btnCadastrarMateriais.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_produto_100;
            this.btnCadastrarMateriais.IdleIconRightImage = null;
            this.btnCadastrarMateriais.IndicateFocus = false;
            this.btnCadastrarMateriais.Location = new System.Drawing.Point(9, 190);
            this.btnCadastrarMateriais.Name = "btnCadastrarMateriais";
            this.btnCadastrarMateriais.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnDisabledState.BorderRadius = 12;
            this.btnCadastrarMateriais.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarMateriais.OnDisabledState.BorderThickness = 1;
            this.btnCadastrarMateriais.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnDisabledState.IconLeftImage = null;
            this.btnCadastrarMateriais.OnDisabledState.IconRightImage = null;
            this.btnCadastrarMateriais.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarMateriais.onHoverState.BorderRadius = 12;
            this.btnCadastrarMateriais.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarMateriais.onHoverState.BorderThickness = 1;
            this.btnCadastrarMateriais.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarMateriais.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarMateriais.onHoverState.IconLeftImage = null;
            this.btnCadastrarMateriais.onHoverState.IconRightImage = null;
            this.btnCadastrarMateriais.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnIdleState.BorderRadius = 12;
            this.btnCadastrarMateriais.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarMateriais.OnIdleState.BorderThickness = 1;
            this.btnCadastrarMateriais.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarMateriais.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_produto_100;
            this.btnCadastrarMateriais.OnIdleState.IconRightImage = null;
            this.btnCadastrarMateriais.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnPressedState.BorderRadius = 12;
            this.btnCadastrarMateriais.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarMateriais.OnPressedState.BorderThickness = 1;
            this.btnCadastrarMateriais.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarMateriais.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarMateriais.OnPressedState.IconLeftImage = null;
            this.btnCadastrarMateriais.OnPressedState.IconRightImage = null;
            this.btnCadastrarMateriais.Size = new System.Drawing.Size(50, 43);
            this.btnCadastrarMateriais.TabIndex = 2;
            this.btnCadastrarMateriais.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCadastrarMateriais.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCadastrarMateriais.TextMarginLeft = 0;
            this.btnCadastrarMateriais.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnCadastrarMateriais, "Cadastrar Materiais");
            this.bunifuToolTip1.SetToolTipIcon(this.btnCadastrarMateriais, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnCadastrarMateriais, "");
            this.btnCadastrarMateriais.UseDefaultRadiusAndThickness = true;
            this.btnCadastrarMateriais.Click += new System.EventHandler(this.btnCadastrarMateriais_Click);
            // 
            // btnCadastrarClientes
            // 
            this.btnCadastrarClientes.AllowAnimations = true;
            this.btnCadastrarClientes.AllowMouseEffects = true;
            this.btnCadastrarClientes.AllowToggling = false;
            this.btnCadastrarClientes.AnimationSpeed = 200;
            this.btnCadastrarClientes.AutoGenerateColors = false;
            this.btnCadastrarClientes.AutoRoundBorders = false;
            this.btnCadastrarClientes.AutoSizeLeftIcon = true;
            this.btnCadastrarClientes.AutoSizeRightIcon = true;
            this.btnCadastrarClientes.BackColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCadastrarClientes.BackgroundImage")));
            this.btnCadastrarClientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarClientes.ButtonText = "";
            this.btnCadastrarClientes.ButtonTextMarginLeft = 0;
            this.btnCadastrarClientes.ColorContrastOnClick = 45;
            this.btnCadastrarClientes.ColorContrastOnHover = 45;
            this.btnCadastrarClientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnCadastrarClientes.CustomizableEdges = borderEdges8;
            this.btnCadastrarClientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCadastrarClientes.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCadastrarClientes.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCadastrarClientes.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarClientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCadastrarClientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarClientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCadastrarClientes.IconMarginLeft = 11;
            this.btnCadastrarClientes.IconPadding = 10;
            this.btnCadastrarClientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCadastrarClientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCadastrarClientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCadastrarClientes.IconSize = 25;
            this.btnCadastrarClientes.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.IdleBorderRadius = 12;
            this.btnCadastrarClientes.IdleBorderThickness = 1;
            this.btnCadastrarClientes.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_lugar_coletivo_seguro_100;
            this.btnCadastrarClientes.IdleIconRightImage = null;
            this.btnCadastrarClientes.IndicateFocus = false;
            this.btnCadastrarClientes.Location = new System.Drawing.Point(9, 122);
            this.btnCadastrarClientes.Name = "btnCadastrarClientes";
            this.btnCadastrarClientes.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnDisabledState.BorderRadius = 12;
            this.btnCadastrarClientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarClientes.OnDisabledState.BorderThickness = 1;
            this.btnCadastrarClientes.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnDisabledState.IconLeftImage = null;
            this.btnCadastrarClientes.OnDisabledState.IconRightImage = null;
            this.btnCadastrarClientes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarClientes.onHoverState.BorderRadius = 12;
            this.btnCadastrarClientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarClientes.onHoverState.BorderThickness = 1;
            this.btnCadastrarClientes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarClientes.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnCadastrarClientes.onHoverState.IconLeftImage = null;
            this.btnCadastrarClientes.onHoverState.IconRightImage = null;
            this.btnCadastrarClientes.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnIdleState.BorderRadius = 12;
            this.btnCadastrarClientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarClientes.OnIdleState.BorderThickness = 1;
            this.btnCadastrarClientes.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarClientes.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_lugar_coletivo_seguro_100;
            this.btnCadastrarClientes.OnIdleState.IconRightImage = null;
            this.btnCadastrarClientes.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnPressedState.BorderRadius = 12;
            this.btnCadastrarClientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCadastrarClientes.OnPressedState.BorderThickness = 1;
            this.btnCadastrarClientes.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnCadastrarClientes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCadastrarClientes.OnPressedState.IconLeftImage = null;
            this.btnCadastrarClientes.OnPressedState.IconRightImage = null;
            this.btnCadastrarClientes.Size = new System.Drawing.Size(50, 43);
            this.btnCadastrarClientes.TabIndex = 1;
            this.btnCadastrarClientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCadastrarClientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCadastrarClientes.TextMarginLeft = 0;
            this.btnCadastrarClientes.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.btnCadastrarClientes, "Cadastar Clientes");
            this.bunifuToolTip1.SetToolTipIcon(this.btnCadastrarClientes, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnCadastrarClientes, "");
            this.btnCadastrarClientes.UseDefaultRadiusAndThickness = true;
            this.btnCadastrarClientes.Click += new System.EventHandler(this.btnCadastrarClientes_Click);
            // 
            // btnOpcoesMenu
            // 
            this.btnOpcoesMenu.AllowAnimations = true;
            this.btnOpcoesMenu.AllowMouseEffects = true;
            this.btnOpcoesMenu.AllowToggling = false;
            this.btnOpcoesMenu.AnimationSpeed = 200;
            this.btnOpcoesMenu.AutoGenerateColors = false;
            this.btnOpcoesMenu.AutoRoundBorders = false;
            this.btnOpcoesMenu.AutoSizeLeftIcon = true;
            this.btnOpcoesMenu.AutoSizeRightIcon = true;
            this.btnOpcoesMenu.BackColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.BackColor1 = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOpcoesMenu.BackgroundImage")));
            this.btnOpcoesMenu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcoesMenu.ButtonText = "";
            this.btnOpcoesMenu.ButtonTextMarginLeft = 0;
            this.btnOpcoesMenu.ColorContrastOnClick = 45;
            this.btnOpcoesMenu.ColorContrastOnHover = 45;
            this.btnOpcoesMenu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnOpcoesMenu.CustomizableEdges = borderEdges9;
            this.btnOpcoesMenu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOpcoesMenu.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOpcoesMenu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnOpcoesMenu.ForeColor = System.Drawing.Color.White;
            this.btnOpcoesMenu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpcoesMenu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcoesMenu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOpcoesMenu.IconMarginLeft = 11;
            this.btnOpcoesMenu.IconPadding = 10;
            this.btnOpcoesMenu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOpcoesMenu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcoesMenu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOpcoesMenu.IconSize = 25;
            this.btnOpcoesMenu.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.IdleBorderRadius = 12;
            this.btnOpcoesMenu.IdleBorderThickness = 1;
            this.btnOpcoesMenu.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.IdleIconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_tabela_de_conteúdo_100;
            this.btnOpcoesMenu.IdleIconRightImage = null;
            this.btnOpcoesMenu.IndicateFocus = false;
            this.btnOpcoesMenu.Location = new System.Drawing.Point(9, 6);
            this.btnOpcoesMenu.Name = "btnOpcoesMenu";
            this.btnOpcoesMenu.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnDisabledState.BorderRadius = 12;
            this.btnOpcoesMenu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcoesMenu.OnDisabledState.BorderThickness = 1;
            this.btnOpcoesMenu.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnDisabledState.IconLeftImage = null;
            this.btnOpcoesMenu.OnDisabledState.IconRightImage = null;
            this.btnOpcoesMenu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnOpcoesMenu.onHoverState.BorderRadius = 12;
            this.btnOpcoesMenu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcoesMenu.onHoverState.BorderThickness = 1;
            this.btnOpcoesMenu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnOpcoesMenu.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(58)))), ((int)(((byte)(58)))));
            this.btnOpcoesMenu.onHoverState.IconLeftImage = null;
            this.btnOpcoesMenu.onHoverState.IconRightImage = null;
            this.btnOpcoesMenu.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnIdleState.BorderRadius = 12;
            this.btnOpcoesMenu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcoesMenu.OnIdleState.BorderThickness = 1;
            this.btnOpcoesMenu.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnOpcoesMenu.OnIdleState.IconLeftImage = global::PROJETO_SISTEMA_DE_VENDAS__MARMORARIA_BELLAS_PEDRAS_.Properties.Resources.icons8_tabela_de_conteúdo_100;
            this.btnOpcoesMenu.OnIdleState.IconRightImage = null;
            this.btnOpcoesMenu.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnPressedState.BorderRadius = 12;
            this.btnOpcoesMenu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcoesMenu.OnPressedState.BorderThickness = 1;
            this.btnOpcoesMenu.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnOpcoesMenu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOpcoesMenu.OnPressedState.IconLeftImage = null;
            this.btnOpcoesMenu.OnPressedState.IconRightImage = null;
            this.btnOpcoesMenu.Size = new System.Drawing.Size(50, 43);
            this.btnOpcoesMenu.TabIndex = 0;
            this.btnOpcoesMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOpcoesMenu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOpcoesMenu.TextMarginLeft = 0;
            this.btnOpcoesMenu.TextPadding = new System.Windows.Forms.Padding(0);
            this.toolTip1.SetToolTip(this.btnOpcoesMenu, "Opções");
            this.bunifuToolTip1.SetToolTip(this.btnOpcoesMenu, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnOpcoesMenu, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnOpcoesMenu, "");
            this.btnOpcoesMenu.UseDefaultRadiusAndThickness = true;
            this.btnOpcoesMenu.Click += new System.EventHandler(this.btnOpcoesMenu_Click);
            // 
            // form_Principal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(36)))), ((int)(((byte)(36)))));
            this.ClientSize = new System.Drawing.Size(1268, 635);
            this.Controls.Add(this.pnlDesktop);
            this.Controls.Add(this.btnMinimizarJanela);
            this.Controls.Add(this.btnFecharJanela);
            this.Controls.Add(this.pnlMenu);
            this.Controls.Add(this.bunifuGroupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "form_Principal";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.pnlMenu.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel pnlMenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOpcoesMenu;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFecharJanela;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMinimizarJanela;
        private System.Windows.Forms.ToolTip toolTip1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCadastrarClientes;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCadastrarMateriais;
        private Bunifu.UI.WinForms.BunifuPanel pnlDesktop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFinanceiro;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCadastrarServicos;
        private System.Windows.Forms.Timer timer1;
    }
}

